server:
  port: 8082

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jms:
    servicebus:
      connection-string: # TODO: add connection string
      topic-client-id: subscriberOlejar # TODO: add subscription name (subscriberYourName)
      pricing-tier: standard

logging:
  level:
    cz.inventi.kpj: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.security: DEBUG
